# code/analyses/rtestim/_common.R
#
# rtestim-SEIR retro fit with girt (LOG deconv), apples-to-apples with EpiNow2.
#
# GI: the TRUE SEIR-implied generation interval, discrete Gamma(theor_mean,
# theor_sd) = (8.41, 3.97) from seir_params.rds.  All methods (MechRt + the
# estimateR/EpiEstim/rtestim/EpiLPS baselines, regenerated by regen_baselines.R)
# use this same true GI.  EpiNow2's cached fits still use the earlier rounded
# target (8.4, 3.8) because they are produced on the cluster (epinow2_fit_one.R)
# and were not re-run; see that script.  Severity 1, pre-day-0
# "pre_hist" seed (rate = median(y[1:3])) folded into pre_I (P_hat correction)
# and the offset:
#   Lambda_s = sum_k g_k X_{s-k} + pre_hist * shifted_survival(g)_s
#   offset  += pre_hist * shifted_survival(pi_EY)
# build_gi_design(seed_rate=, pre_hist_rate=) handles both.

.find_repo_root <- function() {
  a <- commandArgs(FALSE); f <- sub("^--file=", "", a[grep("^--file=", a)])
  d <- if (length(f)) tryCatch(dirname(normalizePath(f[1])), error = function(e) getwd()) else getwd()
  for (i in 1:9) { if (all(c("data","results","figures","code") %in% list.files(d))) return(normalizePath(d)); p <- dirname(d); if (p == d) break; d <- p }
  stop("repo root not found")
}
repo_root   <- .find_repo_root()
data_dir    <- file.path(repo_root, "data")
results_dir <- file.path(repo_root, "results")
figures_dir <- file.path(repo_root, "figures")
source(file.path(repo_root, "code", "girt.R"))
suppressPackageStartupMessages({ library(dplyr); library(tibble) })

rt_data_dir    <- file.path(data_dir, "sim", "rtestim")
rt_results_dir <- file.path(results_dir, "sim", "rtestim")   # flat: epinow2_*/, fit_*.rds, girt/, table csvs
rt_figures_dir <- file.path(figures_dir, "sim", "rtestim")   # flat: the 3 deliverable images

# rtestim's exact delay discretization (matches retro_benchmark.R).
discrete_gamma <- function(mean_x, sd_x, k = 60) {
  shape <- (mean_x / sd_x)^2; rate <- mean_x / sd_x^2; p <- numeric(k)
  p[1] <- pgamma(1.5, shape, rate)
  if (k >= 2) p[2:k] <- pgamma((2:k) + 0.5, shape, rate) - pgamma((2:k) - 0.5, shape, rate)
  p / sum(p)
}
auto_k_gamma <- function(mean_x, sd_x, tol = 1e-4, k_min = 5) {
  shape <- (mean_x / sd_x)^2; rate <- mean_x / sd_x^2
  max(k_min, as.integer(ceiling(qgamma(1 - tol, shape, rate))))
}

rt_cfg <- list(N = 1e8, severity = 1.0, knot_step = 5L, spline_degree = 3L,
               lam_grid = 10^seq(1, 6, length.out = 30), cv_folds = 5L, level = 0.95,
               date0 = as.Date("2020-01-01"))
sei_par <- readRDS(file.path(rt_data_dir, "seir_params.rds"))

rt_delays <- function(sit = "fake") {
  p <- sei_par[sei_par$si_type == sit, ]
  pi_L  <- discrete_gamma(p$mean_L,  p$sd_L,  k = auto_k_gamma(p$mean_L,  p$sd_L))
  pi_D  <- discrete_gamma(p$mean_D,  p$sd_D,  k = auto_k_gamma(p$mean_D,  p$sd_D))
  pi_EY <- discrete_gamma(p$mean_EY, p$sd_EY, k = auto_k_gamma(p$mean_EY, p$sd_EY))
  # GI: the true SEIR-implied generation interval, discrete Gamma(theor_mean, theor_sd).
  gi_m <- p$theor_mean; gi_s <- p$theor_sd
  g_epi <- discrete_gamma(gi_m, gi_s, k = auto_k_gamma(gi_m, gi_s))
  list(pi_EY = pi_EY, pi_L = pi_L, pi_D = pi_D, surv_IR = c(1, 1 - cumsum(pi_D)),
       g = g_epi, mean_D = p$mean_D)
}

# Build the girt design + CV lambdas for one rtestim scenario (smooth or jump).
rt_design_cv <- function(y, dates, dl, jump_times = NULL) {
  max_t <- length(y) - 1L
  X_hat <- gi_deconvolve_exposures(y, pi_EY = dl$pi_EY, severity_rate = rt_cfg$severity,
                                   link = "log", burn_in = 0L)$X_hat
  pre_hist <- median(y[1:min(3L, length(y))])
  d <- suppressWarnings(build_gi_design(
    E_star = X_hat, g = dl$g, pi_EY = dl$pi_EY, max_time = max_t, inf_inc = y,
    y_min_count = 0, y_min_start = 0, y_min_end = 0, spline_degree = rt_cfg$spline_degree,
    knot_step = rt_cfg$knot_step, first_rt_index = 0L, dates = dates, dow_dates = NULL,
    jump_times = jump_times, pre_hist_rate = pre_hist, seed_rate = pre_hist))
  d <- gi_apply_severity_to_design(d, rep(rt_cfg$severity, length(y)))
  sel <- gi_select_lambda_cv(d, lam_grid = rt_cfg$lam_grid, tail = "linear", nfold = rt_cfg$cv_folds,
                             cv_select_rule = "1se", error_measure = "deviance")
  lam_1se <- if (!is.null(sel$best_lam_1se) && is.finite(sel$best_lam_1se)) sel$best_lam_1se else sel$best_lam
  list(design = d, lam_1se = lam_1se, lam_min = sel$best_lam_min, dates = dates, mean_D = dl$mean_D)
}
# Extract an Rt band at a given lambda + overdispersion setting.
rt_band <- function(dc, lam, overdispersion = FALSE) {
  fit <- gi_solve(dc$design, lam, tail = "linear")
  rt <- gi_extract_rt(fit, dc$design, lam = lam,
                      level = rt_cfg$level, overdispersion = overdispersion)
  rt$date <- dc$dates[rt$day + 1L]
  rt[, c("date","day","Rt_mean","Rt_lo","Rt_hi")]
}
# Convenience: smooth fit at lam_1se (od=FALSE) -- matches cached fit_ours$rt.
fit_rtestim_girt <- function(y, dates, dl, jump_times = NULL) {
  dc <- rt_design_cv(y, dates, dl, jump_times)
  list(rt = rt_band(dc, dc$lam_1se, overdispersion = FALSE), lam = dc$lam_1se, dc = dc)
}
